x-develop: &develop
  watch:
    - action: sync
      path: .
      target: /app
    - action: rebuild
      path: .
      ignore:
        - "**"
        - "!Dockerfile"
        - "!.dockerignore"
        - "!**/package.json"

services:
  web:
    build: .
    env_file: .env
    command: ["dev"]
    ports:
      - "127.0.0.1:3000:3000"
    develop: *develop

  mysql:
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: recreate-t3-app
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: