x-develop: &develop
  watch:
    - action: sync
      path: .
      target: /app
    - action: rebuild
      path: .
      ignore:
        - "**"
        - "!Dockerfile"
        - "!.dockerignore"
        - "!**/package.json"

services:
  web:
    build: .
    env_file: .env
    command: ["dev"]
    ports:
      - "127.0.0.1:3000:3000"
    develop: *develop
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: recreate-t3-app
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u root -ppassword"
      timeout: 5s
      interval: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    
  mailpit:
    image: axllent/mailpit:v1.20.5
    ports:
      - "127.0.0.1:8025:8025"
      - "127.0.0.1:1025:1025"
    environment:
       - MP_DATA_FILE=/data/mailpit.db
    volumes:
      - mailpit_data:/data

volumes:
  mysql_data:
  mailpit_data: